development:
  :concurrency: 5

production:
  :concurrency: 10

:max_retries: 1

:queues:
  - default
  - sk
  - aj

# sidekiq-scheduler
:schedule:
  stats_collector:
    #cron: '0 * * * * *'       # Runs once per minute
    every: 5s
    class: StatsCollectorJob  # Running sidekiq directly
